---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(p8105.datasets)
library(plotly)
```

Column {data-width = 600}
---------------------------
### Chart A: Max temperature in Central Park, Waikiki, Waterhole from 2017 to 2018
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df %>%
  plot_ly(x = ~date, y = ~tmax,  color = ~name, type = "scatter", colors = "viridis")
```

Column {data-width=400}
---------------------------

### Chart B: Distribution of max temperature in three place from 2017 to 2018

```{r}
weather_df %>%
  plot_ly(x = ~name, y = ~tmax, color = ~name, type="violin", colors = "viridis") 
```

### Chart C:

```{r}
weather_df %>%
  plot_ly(x = ~name, y = ~tmin, color = ~name, type = "box", colors = "viridis")
```